title: TIKI-SHARE dev
description: All you need to know to use the TIKI-SHARE system and API 
theme: just-the-docs

url: https://tiki-sup.github.io/tiki-share-documentation/

aux_links:
  TIKI-SHARE: https://tiki-share.com
